-- AlterTable
ALTER TABLE "potential_participants" ALTER COLUMN "first_name" SET DATA TYPE TEXT,
ALTER COLUMN "last_name" SET DATA TYPE TEXT,
ALTER COLUMN "phone_number" SET DATA TYPE TEXT,
ALTER COLUMN "email" SET DATA TYPE TEXT,
ALTER COLUMN "county" SET DATA TYPE TEXT,
ALTER COLUMN "zip" SET DATA TYPE TEXT,
ALTER COLUMN "referrer_first_name" SET DATA TYPE TEXT,
ALTER COLUMN "referrer_last_name" SET DATA TYPE TEXT,
ALTER COLUMN "referrer_phone" SET DATA TYPE TEXT,
ALTER COLUMN "referrer_email" SET DATA TYPE TEXT,
ALTER COLUMN "referral_source" SET DATA TYPE TEXT,
ALTER COLUMN "referral_business_name" SET DATA TYPE TEXT,
ALTER COLUMN "client_of_mdrrs" SET DATA TYPE TEXT,
ALTER COLUMN "staff_submit_referral_to_mdrrs" SET DATA TYPE TEXT,
ALTER COLUMN "long_covid_syndrome" SET DATA TYPE TEXT,
ALTER COLUMN "is_ms_resident" SET DATA TYPE TEXT,
ALTER COLUMN "is_age_16_to_70" SET DATA TYPE TEXT,
ALTER COLUMN "desire_to_continue_work" SET DATA TYPE TEXT,
ALTER COLUMN "wants_to_work_if_unemployed" SET DATA TYPE TEXT,
ALTER COLUMN "not_involving_other_off" SET DATA TYPE TEXT,
ALTER COLUMN "eligibility_criteria" SET DATA TYPE TEXT;
